econtract:
  datasource:
    url: jdbc:mysql://10.153.99.58:33061/econtract?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: econtract
    password: '!IVHH0E#dx'

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  log: /usr/data/logs/            #日志存放的位置
  level: ERROR            #日志的级别
  maxHistory: 30        #日志的最大保留时间

logging:
  config: classpath:log4j-spring.xml



