econtract:
  datasource:
    url: jdbc:mysql://dzht-mysql:3306/econtract?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
#    url: jdbc:mysql://10.0.75.1:3306/econtract?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml

app:
  log: logs/            #日志存放的位置
  level: INFO           #日志的级别
  maxHistory: 30        #日志的最大保留时间

logging:
  config: classpath:log4j-spring.xml

